name: Create GitHub Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Create tar.gz files
        run: bash ./release.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./release/*.tar.gz